### ISSUE TITLE
Create testbench for the Slave RTL verification and reuse the Master VIP

### ISSUE THREAD

**Issue by Gopalsuthar2308** [mbits-mirafra/axi4Lite_avip#3]
Inside the VIPMasterRTLSlave example directory create the required files for the testbench and reuse our Master VIP.
Then connect with the Slave RTL and make sure that the compilation is free.

**Comment by mahadevaswamy05** [comment]
Created the base test for the slave RTL and reused the Master VIP Env and compilation free.
