### ISSUE TITLE
Based on Discussions on 28th Sep update Our VIP 

### ISSUE THREAD

**Issue by Gopalsuthar2308** [mbits-mirafra/axi4Lite_avip#8]
Here we're updating the all discussion points.

**Comment by mahadevaswamy05** [comment]
1. Inside the base test, we are using the hierarchy way to get the values of the particular agent config file.  

We added one local handle inside the base tests for the agent config and we are using this handle for assigning values for the config variables at last we are assigning this local handle to the main agent config handle for all 4 agents.

**Comment by mahadevaswamy05** [comment]
2. We are using the magic number assigning to agent config variable So we updated the all magic numbers to writing the parameter  variables

**Comment by mahadevaswamy05** [comment]
3. We are writing the wait counter for all handshaking signals in particular channels but we haven't written the response channel handshake wait counter.
So we wrote the wait counter for the response channel.

**Comment by mahadevaswamy05** [comment]
4. We are writing the wait counter for all handshaking signals in particular channels and If the wait counter reaches the maximum number then we need to add a display like handshake signals error for the particular channel.

**Comment by mahadevaswamy05** [comment]
5. Earlier we wrote only one config defaultReady variable for All 5 channels ready,
So we updated this config defaultReady variable for all channel readys like defaultAwready, defaultWready , defaultBready, defaultArready and defaultRready

**Comment by mahadevaswamy05** [comment]
6. We wrote the address earlier just 8 bits of the maximum address and this updated to min address = 32'h0000_0000 and Maximum address is 32'hffff_ffff for all block-level global packages.

**Comment by mahadevaswamy05** [comment]
7. we updated the scoreboard check_phase like inside the if conditions itself we are checking the FIFO weather zero or not and there itself fifo is not zero then printing the values by using the uvm_error.

**Comment by mahadevaswamy05** [comment]
8. we added the coverpoints for the particular config variables and we are able to see the coverage report inside Firefox.

**Comment by mahadevaswamy05** [comment]
9. Updated the address cover points, and inside the bins, we mention the minimum and maximum address range and that is what we are providing from the agent config, which is monitoring whether the address is covered within range or not.  

Actually that agent config variable of the minimum and maximum values is not woking inside the bins, So we removed that.

**Comment by mahadevaswamy05** [comment]
10. Inside the HDL Top we have the Generate block, which should go inside the master agent file But we don't have the master agent and if will add then also we need to call or generate inside the HDL top module. 

- we added the master agent BFM and slave agent BFM inside we are writing the generate block for the write agent and read agent.

**Comment by mahadevaswamy05** [comment]
11. Inside the BFM or assertions or cover property file we should write the config db get method to receive the config variables  values from the agent config db set method 

- We added and it's working well.
